version: '2.3'

services:
  # video detection underconstruct
  # waiting for Naii docker-image
  socket:
    build: ./socket
    command: sh /socket/runserver.sh
    ports:
      - 5000:5000
    volumes:
      - ./socket:/socket
    restart: always

  web:
    image: nginx:1.17.2-alpine
    ports:
      - 8080:80
    volumes:
      - ./web/:/usr/share/nginx/html/
    depends_on:
      - socket

  videoDection:
    build: ./video_dection
    runtime: nvidia
    command: python /video_dection/video_dection.py
    volumes:
      - ./video_dection:/video_dection
    depends_on:
      - web