version: '2'

services:
  # video detection underconstruct
  # waiting for Naii docker-image
  socket:
    build: ./socket
    command: sh /socket/runserver.sh
    ports:
      - 5000:5000
    volumes:
      - ./socket:/socket
    restart: always

  web:
    image: nginx:1.17.2-alpine
    ports:
      - 8080:80
    volumes:
      - ./web/:/usr/share/nginx/html/
    depends_on:
      - socket
