version: '2.3'
networks:
  socket:
    external: true
services:

  zmq:
    build: ./zmq
    command: sh /zmq/runserver.sh
    ports:
      - 5560:5560
    networks:
      - socket
  server:
    build: ./server
    command: python server.py
    networks: 
      - socket
    ports: 
      - 5000:5000

  video_detection:
    build: ./video_detection
    runtime: nvidia
    command: python3 /video_detection/video_detection.py
    volumes:
      - ./models/:/video_detection/darknet/models/
    depends_on:
      - zmq
    devices:
      - /dev/video0:/dev/video0
    networks:
      - socket
